image: nixos/nix:latest

variables:
  NIX_CONF_DIR: "/etc/nix"

before_script:
  - echo 'experimental-features = nix-command flakes' > $NIX_CONF_DIR/nix.conf

check:
  script:
    - nix flake check --impure --show-trace --accept-flake-config
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
